# MAYAChain monitoring bot configuration file
# Rename it to "config.yaml"

log_level: INFO
colorful_logs: false

sleep_before_start: 3
startup_step_delay: 3.0

sentry:
  url: ""

web3:
  ETH:
    rpc: "https://mainnet.infura.io/v3/1234abdc9876610efef"
  AVAX:
    rpc: "https://api.avax.network/ext/bc/C/rpc"
  BSC:
    rpc: "https://bscrpc.com"
  ARB:
    rpc: "https://arb1.arbitrum.io/rpc"
  cache_expire: 30d
  retries: 3
  retry_wait: 2s


thor:
  network_id: "mainnet"

  node:
    node_url: "https://mayanode.mayachain.info/"
    rpc_node_url: "https://tendermint.mayachain.info/"
    backup_node_url: "https://mayanode.mayachain.info/"

  midgard:
    tries: 3
    public_url: "https://midgard.mayachain.info/"

  timeout: 20.0

  stable_coins:
    - ETH.USDC-0XA0B86991C6218B36C1D19D4A2E9EB0CE3606EB48
    - ETH.USDT-0XDAC17F958D2EE523A2206206994597C13D831EC7
    - KUJI.USK
    - ARB.USDC-0XAF88D065E77C8CC2239327C5EDB3A432268E5831
    - ARB.USDT-0XFD086BC7CD5C481DCC9C85EBE478A1C0B69FCBB9

  circulating_supply:
    # https://docs.etherscan.io/getting-started/creating-an-account
    ether_scan_key: PLEASEPUTANETHERSCANKEYHERE
    cache_time: 10m


personal:
  max_fails: 3  # (!) new
  rate_limit:
    number: 50
    period: 5m
    cooldown: 1h

  scheduler:
    enabled: true
    poll_interval: 10s


telegram:
  bot:
    token: "insert the bot token from @BotFather here"
    username: "MayaInfoBot"
  common:
    loading_sticker: CAACAgIAAxkBAAIRx1--Tia-m6DNRIApk3yqmNWvap_sAALcAAP3AsgPUNi8Bnu98HweBA

  admins:
    - 12345  # List of TG admins

  buffer_chat: -12334  # a chat for uploading temporary photos (like photo-hosting), add this bot to it

  menu:
    node_op_tools:
      enabled: true

  inline_bot:
    enabled: true
    cache_time: 5m


discord:
  enabled: true
  bot:
    token: "token.for.discord.bot"


slack:
  enabled: true
  bot:
    app_token: xapp-1234134567
    client_id: "123.345"
    client_secret: 1234567890abcdef
    singing_secret: 1234567890abcdef


twitter:
  enabled: true
  is_mock: false
  bot:
    consumer_key: "111"
    consumer_secret: "222"
    access_token: "333"
    access_token_secret: "444"


web:
  debug: false
  port: 8077
  host: 0.0.0.0
  public_url: https://todo.org
  serve_front_end: false  # false on production, this is work for nginx


broadcasting:
  startup_delay: 10s  # skip all messages during this period of time until flood settles down

  channels:
    - type: telegram
      name: "@MayaAlerts"  # live channel
      lang: eng
#    - type: discord
#      name: 322323232323  # channel ID
#      lang: rus
    - type: twitter
      lang: eng-tw


node_op_tools:
  enabled: true

  watchdog:
    enabled: true
    disconnected_cable_timeout: 20m
  types:
    chain_height:
      # 'most_common' or 'max' or  'max_committee' (default)
      top_height_estimation_method: 'max_committee'
      min_committee_members: 3
    online_service:
      tcp_timeout: 1  # sec
      group_size: 60


native_scanner:
  enabled: true

  max_attempts_per_block: 8

  reserve_address: "maya1dheycdevq39qlkxs2a6wuuzyn4aqxhve4hc8sm"

  prohibited_addresses:
    - "maya1g98cy3n9mmjrpn0sxmn63lztelera37n8yyjwl"

  user_counting:
    exclude_addresses:
      - "maya1g98cy3n9mmjrpn0sxmn63lztelera37n8yyjwl"

  db:
    ttl: 7d


names:
  thorname:
    enabled: true
    expire: 48h

  preconfig:
    "maya1dheycdevq39qlkxs2a6wuuzyn4aqxhve4hc8sm": "Reserve"
    "maya17gw75axcnr8747pkanye45pnrwk7p9c3chd5xu": "Bond Module"
    "maya1g98cy3n9mmjrpn0sxmn63lztelera37n8yyjwl": "Asgard"

  affiliates:
    wr: THORWallet
    ss: ShapeShift
    t: THORSwap
    tr: Trust iOS
    te-ios: Trust iOS
    te: "Trust Android"
    rg: "Rango Exchange"
    commission: Ferz
    dx: Asgardex
    dcf: DecentralFi
    ej: EdgeWallet
    xdf: XDEFI
    cb: CoinBot
    runifier: Runifier
    0xbami: Unizen
    ds: Defispot
    eld: "El Dorito"
    cs: CacaoSwap
    kf: "Kensho Finance"
    moca: "Moca"
    mc: "Moca"
    ma: "Moca"
    mo: "Moca"
    ts: "THORSwap"
    dcg: "Dash Core"
    leo: "LeoDex"
    tt: "Turbo Trade"
    OS: "Osaia"
    va: "Vultisig Android"
    vi: "Vultisig iOS"
    v0: "Vultisig"
    dp: "Astrolescent"
    oci: "Ociswap"
    sk: "SwapKit"
    DPH: "Delphibets"
    SSP: "ShardSpace"
    be: "WinBit32"
    is: "InstaSwap"
    
tx:
  enabled: true

  # Everything except SWAPS!
  max_age: 2d
  fetch_period: 60
  tx_per_batch: 50
  max_page_deep: 5
  max_tx_per_single_message: 6

  ignore_donates: true

  announce_pending_after_blocks: 500

  add_date_if_older_than: 2h

  exclamation:
    fee_usd_limit: 3000
    ilp_usd_limit: 5000
    slip_usd_limit: 5000

  curve:
    - depth: 10k
      percent: 12
    - depth: 100k
      percent: 8
    - depth: 1m
      percent: 4
    - depth: 10m
      percent: 2

  liquidity:
    enabled: true
    min_usd_total: 10000
    curve_mult: 0.8

    also_trigger_when:
      ilp_paid_usd_greater: 5000
      affiliate_fee_usd_greater: 1000

    savers:
      enabled: true
      min_usd_total: 100
      curve_mult: 0.00008

  swap:
    enabled: true
    min_usd_total: 20000
    curve_mult: 0.3

    also_trigger_when:
      dex_aggregator_used:
        min_usd_total: 20000
      affiliate_fee_usd_greater: 500
      streaming_swap:
        volume_greater: 25000
        notify_start: true

  donate:
    enabled: true
    min_usd_total: 5000
    curve_mult: 0.075

  refund:
    enabled: true
    min_usd_total: 50000
    curve_mult: 0.1
    cooldown: 20m  # (!) new

  dex_aggregator_update:
    enabled: true
    cooldown: 4d

  show_add_more: false


price:
  enabled: true
  fetch_period: 60
  global_cd: 12h
  change_cd: 1h
  percent_change_threshold: 5
  price_graph:
    default_period: 7d

  #  cex_reference:
  #    cex: binance
  #    pair: USDT

  ath:
    cooldown: 2m
    stickers:
      - CAACAgIAAxkBAAIPuF-zvf5B1guBsIC8YqQE7jHnNP39AAJkBQACP5XMCgTLN7BUdOcAAR4E
      - CAACAgIAAxkBAAIPul-zvjBr2Oc88YgFBNhMtktP4pCeAAJpAgACVp29Cta5X0h7RGRvHgQ
      - CAACAgIAAxkBAAIPvF-zvjn4-XPhcr-M06zZUUvwF700AAIpAAM7cR8iDQ6e_eGNDLUeBA
      - CAACAgIAAxkBAAIPvl-zvkRAYSkjyVNi9QxzovYSDK4DAAKqBQACP5XMCpXI5d6t1J7eHgQ
      - CAACAgIAAxkBAAIPwF-zvlRib5d5xSR1kWEwr0rpTJbIAAISAAP3F4Erq1mdGtkjKYUeBA
      - CAACAgIAAxkBAAIPol-zvRRRPSdC-Sr4lqhKsfNWWh3qAAJPAQACIjeOBHyVl0hMcbwXHgQ
      - CAACAgIAAxkBAAIPsl-zvWI-Ihnnh0BSm6BM6DpYjYuJAAISAAP3F4Erq1mdGtkjKYUeBA
      - CAACAgIAAxkBAAIPuF-zvf5B1guBsIC8YqQE7jHnNP39AAJkBQACP5XMCgTLN7BUdOcAAR4E
      - CAACAgIAAxkBAAIPul-zvjBr2Oc88YgFBNhMtktP4pCeAAJpAgACVp29Cta5X0h7RGRvHgQ
      - CAACAgIAAxkBAAIPvl-zvkRAYSkjyVNi9QxzovYSDK4DAAKqBQACP5XMCpXI5d6t1J7eHgQ
      - CAACAgIAAxkBAAIPwF-zvlRib5d5xSR1kWEwr0rpTJbIAAISAAP3F4Erq1mdGtkjKYUeBA
      - CAACAgIAAxkBAAIPwl-zyp2DJdPINcX6h0ZGesaakaMnAAJ9AwACbbBCA70TLvm2TbpTHgQ
      - CAACAgIAAxkBAAIPyV-zzEtVsFiaAWTVrJ8ROptFYUqjAAJFAAP3F4ErgJFXK7AarK4eBA
      - CAACAgIAAxkBAAJQsV_4emucc8THq6MbytL5PcclEG4NAAKMCwACLw_wBoRsyFANo_xWHgQ
      - CAACAgIAAxkBAAJQs1_4epK5KoxnhAJ3R5akKXpIfN1nAAKfAQACFkJrCmWMf9oXSSAlHgQ
      - CAACAgIAAxkBAAJQxV_4ezGuN6vz35bTfmLe4GPoT6GFAAKlAQACFkJrCqSMglNGCdzWHgQ
      - CAACAgIAAxkBAAKYGmAxSKM0wcVUir6olqJ8GUILs7PEAAI2AwACnNbnCqJFmbVS5co5HgQ
      - CAACAgIAAxkBAAKYGGAxSJmnC6uu7NyUkjwD2uQ2k8Z3AAITAwACnNbnCv7sKag-OU5jHgQ
      - CAACAgIAAxkBAAKYFmAxSI6jczWX5DMkK9N7D5U3arbZAAIDAQACVp29CgLl0XiH5fpPHgQ
      - CAACAgIAAxkBAAKYHGAxSOVmUIJnSALFOQmjvDUUhE8SAAIvAwACnNbnCp7xW8futGVHHgQ
      - CAACAgIAAxkBAAKYHmAxSPKMMhaVi529pPU-_ROhQlB_AAIUAAM7YCQUKWeBEgL3yOoeBA
      - CAACAgIAAxkBAAKYImAxSRLALhyBbigWlLSUzrLaf84mAAJVBgAC-gu2CMHtlUjSy95hHgQ
      - CAACAgIAAxkBAAKYJGAxSSC1U9D67zyg-7RJfjkork8EAAKMAAMWQmsKQo7-Yhc9TeIeBA
      - CAACAgIAAxkBAAKYJmAxST6CTOiOStfQ9CH7hqLiv0iWAAL8BgACRvusBG1XSZhZ24v-HgQ

  divergence:
    enabled: false
    cooldown: 12h

    public:
      min_percent: 1.9
      max_percent: 5.5
    personal:
      enabled: true
      cooldown: 30m

  volume:
    record_tolerance: 1h


token_transfer:
  enabled: true
  fetch_period: 30

  min_usd:
    native: 100000
  cooldown: 10

  flow_summary:
    enabled: true
    cooldown: 1d

  cex_list:
    - none

  ignore_cex2cex: true


queue:
  enabled: true
  fetch_period: 60
  threshold:
    avg_period: 10m
    congested: 20
    free: 2
  cooldown: 3600
  watch_queues:
    - outbound
    - internal
    - swap


net_summary:
  enabled: true
  fetch_period: 120s
  notification:
    cooldown: 6h


pool_churn:
  enabled: true
  notification:
    cooldown: 1h


node_info:
  enabled: true
  fetch_period: 5s  # for it must not be too slow for NodeOp tools accuracy
  geo_ip:
    expire: 48h

  churn:
    filter_nonsense: false

  version:
    enabled: true
    new_version_appears: # node joined/upgraded to unseen version
      enabled: true
      cooldown: 15m
    version_activates: # new active version (minimal active version)
      enabled: true
      cooldown: 15m
    upgrade_progress: # if not all act. nodes run same version, show upgrade progress every cooldown
      enabled: true
      cooldown: 2h
      minimum_nodes: 4
      minimum_progress_step_percent: 5

  bond_tools:
    enabled: true
    log_events: true


constants:
  mimir_change:
    enabled: true
    cooldown: 10m
  fetch_period: 130s

  voting:
    enabled: true
    notification:
      cooldown: 2h
    hide_forever: # (!) new
      - ACCEPT_RADIX


chain_halt_state:
  enabled: true
  fetch_period: 67s
  cooldown: 5m


last_block:
  enabled: false  # notification enabled?
  fetch_period: 30s  # always enabled
  chart:
    estimation_interval: 5m
  stuck_alert:
    time_limit: 120s
    repeat_cooldown: 24h
    chart_duration: 36h
  normal_block_time: 0.16666  # 1 block = 6 sec
  normal_block_speed_deviation_percent: 15
  low_block_speed_percent: -50
  high_block_speed_percent: 50


best_pools:
  enabled: true
  num_of_top_pools: 5
  cooldown: 1d
  fetch_period: 10m


blockchain:
  block_time: # block_time overriding... (optional)
    BTC: 10m
    ETH: 14s


supply:
  enabled: true
  period: 7d


saver_stats:
  enabled: true
  fetch_period: 10m

  notification:
    enabled: true
    period: 3d


wallet_counter:
  enabled: true
  fetch_period: 1h


achievements:
  enabled: true

  cooldown:
    hits_before_cd: 5
    period: 15m


pol:
  enabled: false
  fetch_period: 30m
  notification:
    cooldown: 1d
    allow_when_zero: false


key_metrics:
  enabled: true  # data collection
  fetch_period: 10m
  data_max_age: 36h
  notification:
    enabled: false  # post updates
    cooldown: 7d
