# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: mayachain/v1/x/mayachain/types/genesis.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GenesisState(betterproto.Message):
    """GenesisState defines the capability module's genesis state."""

    pass
